/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarysystem.librarian.boundary;

import java.awt.Frame;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import librarysystem.librarian.controller.CRUDCardController;

/**
 *
 * @author pdc
 */
public class UpdateCardInfo extends javax.swing.JFrame {

    private static Integer borrowercardnumber;

    Frame frame = new Frame();

    /**
     *
     * @return
     */
    public Frame getFrame() {
        return frame;
    }

    /**
     *
     * @param frame
     */
    public void setFrame(Frame frame) {
        this.frame = frame;
    }

    /**
     *
     * @return
     */
    public static Integer getBorrowercardnumber() {
        return borrowercardnumber;
    }

    /**
     *
     * @param borrowercardnumber
     */
    public static void setBorrowercardnumber(Integer borrowercardnumber) {
        UpdateCardInfo.borrowercardnumber = borrowercardnumber;
    }

    /**
     * Creates new form UpdateCardInfo
     *
     * @param borrowercardnumber
     * @param username
     * @param activatedcode
     * @param status
     * @param expireddate
     * @param frame
     */
    public UpdateCardInfo(int borrowercardnumber, String username, Integer activatedcode, String status, String expireddate, Frame frame) {
        initComponents();
        this.borrowercardnumber = borrowercardnumber;
        this.frame = frame;
        jTextFieldUsernameUpdate.setText(username);
        jTextFieldActivatedCodeUpdate.setText(activatedcode.toString());
        jTextFieldExpiredDateUpdate.setText(expireddate);
        if (null != status) {
            switch (status) {
                case "Unactivated":
                    jComboBoxStatusUpdate.setSelectedIndex(0);
                    break;
                case "Activated":
                    jComboBoxStatusUpdate.setSelectedIndex(1);
                    break;
                default:
                    jComboBoxStatusUpdate.setSelectedIndex(2);
                    break;
            }
        }
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldUsernameUpdate = new javax.swing.JTextField();
        jTextFieldActivatedCodeUpdate = new javax.swing.JTextField();
        jComboBoxStatusUpdate = new javax.swing.JComboBox<>();
        jTextFieldExpiredDateUpdate = new javax.swing.JTextField();
        jButtonSubmitUpdate = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Update Borrower Card Information");
        setAlwaysOnTop(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setText("Username");

        jLabel2.setText("Activated Code");

        jLabel3.setText("Status");

        jLabel4.setText("Expired Date");

        jTextFieldActivatedCodeUpdate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldActivatedCodeUpdateKeyTyped(evt);
            }
        });

        jComboBoxStatusUpdate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unactivated", "Activated", "Deactivated"}));

        jButtonSubmitUpdate.setText("Submit");
        jButtonSubmitUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitUpdateActionPerformed(evt);
            }
        });

        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldUsernameUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldExpiredDateUpdate)
                            .addComponent(jTextFieldActivatedCodeUpdate)
                            .addComponent(jComboBoxStatusUpdate, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonClear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSubmitUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonCancel, jButtonClear, jButtonSubmitUpdate});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextFieldActivatedCodeUpdate, jTextFieldExpiredDateUpdate, jTextFieldUsernameUpdate});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldUsernameUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldActivatedCodeUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxStatusUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldExpiredDateUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSubmitUpdate)
                    .addComponent(jButtonClear)
                    .addComponent(jButtonCancel))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSubmitUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitUpdateActionPerformed
        // TODO add your handling code here:
        if (jTextFieldActivatedCodeUpdate.getText().isEmpty() || jTextFieldExpiredDateUpdate.getText().isEmpty() || jTextFieldUsernameUpdate.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Please Fill Data at All Fields !", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                new CRUDCardController().updateCard(borrowercardnumber, jTextFieldUsernameUpdate.getText(), Integer.parseInt(jTextFieldActivatedCodeUpdate.getText()), jComboBoxStatusUpdate.getSelectedIndex(), jTextFieldExpiredDateUpdate.getText());
            } catch (SQLException ex) {
                Logger.getLogger(UpdateBookInfo.class.getName()).log(Level.SEVERE, null, ex);
            }
            super.dispose();
            frame.setAlwaysOnTop(true);
            frame.setEnabled(true);
        }
    }//GEN-LAST:event_jButtonSubmitUpdateActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
        super.dispose();
        frame.setEnabled(true);
        frame.setAlwaysOnTop(true);
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
        jTextFieldUsernameUpdate.setText("");
        jTextFieldExpiredDateUpdate.setText("");
        jTextFieldActivatedCodeUpdate.setText("");
        jComboBoxStatusUpdate.setSelectedIndex(0);
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        frame.setEnabled(true);
        frame.setAlwaysOnTop(true);
    }//GEN-LAST:event_formWindowClosed

    private void jTextFieldActivatedCodeUpdateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldActivatedCodeUpdateKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9')
                || (c == KeyEvent.VK_BACK_SPACE)
                || (c == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldActivatedCodeUpdateKeyTyped

//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(UpdateCardInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(UpdateCardInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(UpdateCardInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(UpdateCardInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new UpdateCardInfo().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonSubmitUpdate;
    private javax.swing.JComboBox<String> jComboBoxStatusUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextFieldActivatedCodeUpdate;
    private javax.swing.JTextField jTextFieldExpiredDateUpdate;
    private javax.swing.JTextField jTextFieldUsernameUpdate;
    // End of variables declaration//GEN-END:variables
}
